//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nvd_lession10.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NvdAccount
    {
        public int NvdID { get; set; }
        public string NvdUserName { get; set; }
        public string NvdPassWord { get; set; }
        public string NvdFullName { get; set; }
        public string NvdEmail { get; set; }
        public string NvdPhone { get; set; }
        public Nullable<bool> NvdActive { get; set; }
    }
}
